apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: d2kxz6obn-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d2kxz6obn-python 
  name: d2kxz6obn-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: d2kxz6obn-python
    weight: 100 
